# .travis.yml file for Travis CI Automated Build configuration
# Version 0.24

language: java

jdk:
   - openjdk7

branches:
  only:
  - java

sudo: required

before_install:
   - sudo apt-get update
   - curl -sL https://deb.nodesource.com/setup | sudo sh

install:
   - sudo apt-get install -y nodejs
   - cd './WebContent'
   - sudo npm install -g bower
   - bower install --config.interactive=false

before_script:
   - cd '..'

script:
   - mvn clean install

deploy:
  provider: s3
  skip_cleanup: true
  acl: public_read_write
  region: us-east-1
  on:
    repo: SungardAS/snapdirector
    branch: java

env:
  global:
  - secure: aoF2yzFmUtob28iRDYagY6pLUU3EqSRUTw2XlZybn3N46qPiQkeQrt/gNtx64WAwIvKKD+qH1OFrgIKTMKGk8Q0GkllvOWtVnbv2ah6oymXJHHhgLL4Fa6gL9R4Kn7y02oqW2ZPSl8kw5t3NWAaCx5ThjSdhByMdVDrPbMSCvwXpiE7iFlh3ihQG16zc0W6qvCLTzS7oclY2GRjY7xBGvI3cimVlxSRrAIUsrkCrNXVwgKgUUEo+abCagSiLPzd2LxHHfC4GdtYgyNw4piMvOdeT0+KmwdsgYjkgVKruXm6CV2sXriTeX0vXKe/Hy+vCSjNYRbpmDKx12uwoPRZ0+8FHzJLz2ESNph7hrOUFd6W40BVFtbGBSMIALfinZ3mtfU2iuIkVki93DZFZQc7tYv8Wb5CmtVW1MKyqhmMu2/ck5qgOsyLllCtuJXAzjzXctcVZmYlOXD2ipXLg2hsh0OTgNvVqSKT0RSKVqzfj67oQwX7kTur1WlRRqjq2AAtjvJtU+4iAo2s4GmgZ8wehFyGpXa83O16ut3jJTscFMzgRjb+Nf+0hezAf8bKXZG+9VoZKPtEDTE69LNHrCJmy4XmsKLh15EHorNCO5MvB3sdNQ7pq0JeU6p6NWs26hrI0Dk8xOZQLD9uz/BjCysGzf4FKR/IOfs0FeGuh+tODEZk=
  - secure: M10xa73RMn3WF3PFpy7edkqCO8g19Pooy5BpB6g5CgRWCNU297J8Q4xY8idq4qCIfjdXApOPAdbWAqlH2JT+bL34DKvWTT8RKSUw9pA85mMt3rhPmWicE4z0mdwSiAZtz+cJyQNDSgLcH6Tj4ozMhPprVbFvd1opcyYSMmr5J4uBeGy+P1nBzDt87bEahFrG1UUDJwbQGO7faeT7CAl23cNhNKwg5a3l0vF6pXcWo71eJcHVls/XncEtrPmWoDWwNgoWvtJqx0XXOoSQ7cSpKcyAHmpCubkmQT4Mpkzj0K33Lz6W03DjJw/vwsMlwA1HmW0IfTwazvp65Q5I8lJH8QH4u8fYOVm274/EvbahKsYFOSSHQD2nHtb90RPgjDFrH9PoweidYcTEgETq29ZpgnAzL6NCMGx/72HZ8f7WxGVkN3nc+GkPIT3COT9kvmG5pwlrpAKfYztdBl25h9Q/KXvKBRoDp5EnV662a6YZnBVcFOCMzQDMzVvcPD6OkA+EBiUkhbjDEz+ong0DgZUJ6qVuxzKJcgt2N7wSWV2qDmx4hkESzFfSegadSEA+jadpVe82v6NHHrxPQuK+nz52BFPf4dFeq08CNExBFQitrFLL+yw9cFArM8C05nI8Vm40m342Ak/AOtmOjYePxjjLpd5yHtip8oAup1FAqbP6Mpk=
  - secure: F0TASYZ0l08BRsQuJTFLzJB9n3dMiQ2AdB+FE30p6bbR4CONDLlqBmNfudTjSakgnf6VkfJWvkeu8gGfSuitMosIlKVwQoUHDwbl+dQ9WRX2nE3HOGtrzYbpQi63qm8apQg2EOT4R0cjsxAJO+mK3J6o72wOeGYjD+xjZ0j6Zy5YJrPyt/MvqEfeTAkUYoe/WvlJ0PNg4Xi5ksjmD+jsggVZgJqj9ekwCjmyIzY+xjLrygDPD3+9qicZ57slXdeOqtIDi4bcN06Tc+uwXzjjIcjpFi6lDv5gTSv2CJkJUpFzE3AZSzza4NOmOpJ/rLQnmUbl9wRl6AWGMzy9Xa3r4FpaKxlB2CMSimFoDwIa6IqCSMsMl7JkECaEcUp2uOuASLtEvpSysMtxaBBhpDF7nTEeIoF7SoS3Y1d1Ak3wqfgF0vVu/qN6p3cW+1nR/7o/vGhVOmMGyO0mh//YzK7s01pJTJsqn2PWCPpgVgTst0Qk2WifUF8FMIbzrHCT9zleXnpsypVr1x6T/ynclpZMHbKex72dPZ04Eoej7Wk+yyYS7V/C17HWNiJEnngrcEUaPxwr1ickLW/EydGxOP+Udsd2qUK2qyTV2NzyxlREcKi6P4YExvk3KkLXOY4CMKIaCN2JoTTMgLlS1qhubcW1jvOqedpzLKSYXPuEHN+J/yM=
  - secure: dJYm2Ob4xVH+2Q6Q+5x50KYeLfilzPyOIAM3+ONoEVcg8Fz8wIhXpqBA3lGrcQmyT/XNJUUziWKIEHrDUt3RpEpCcWG+Rn1c/aUe8uCa3EsFEHwGcupgVjgExVmb8wWE1M6uKeG3Q8VH8xDesT1WmV77gRs9O/YA3UB7tA6KLlfnqTmYW0gS28Wm4S5D8rhQTRAXOXkX7/upCfbfetbk0VSuuz8sVP0kUAhgH4nNvYQMQacM1OBY7sulQ+0qv+TCSByznuPGGgkgXqTQR1bdKbYuq2ldYAKcLkwy8iB/VkrVgGHI5IFkqgJQ3SCiQqAGXDTaDs21NqIPVcmZUhIh5ujWnyc1tqeNxfYtBlzkl70cWuMrw8+wFydQIXRcbbtzUvqm2P0++BUuADABta+7EHBAvpSUuXI4E9QRuAW+D/rQxLrW7IUkoIux4/dQpCY4u50L+vMxbz48XtvMtEXeJmlvFSw3/h5DIINA1SwyA+BL6U2enWGJfGpnPKVXMM0zU+xuRNlsImUpReJlmKPu6Azh/ztK2PKQRnT+QE4/CizW0o6jw/ORVoehXuQsLyns9r6who9n69cjj3LhAsOpQbN1vVBmM5DjtPxE1gp9Ly1KpUxbnIZfD2YnunpnSf/BxJvfc81Z54QrW3DNTpTr4KcvQ4T8UVzeqgX/EN6IDzw=
