# .travis.yml file for Travis CI Automated Build configuration
# Version 0.41

language: java

jdk:
  - openjdk7

branches:
  only:
  - java

sudo: required

before_install:
  - sudo apt-get update
  - curl -sL https://deb.nodesource.com/setup | sudo sh

install:
  - sudo apt-get install -y nodejs
  - cd './WebContent'
  - sudo npm install -g bower
  - bower install --config.interactive=false

before_script:
  - cd '..'

script:
  - mvn clean install

deploy:
  provider: s3
  bucket: "com.sungardas.releases"
  endpoint: "s3-us-east-1.amazonaws.com"
  skip_cleanup: true
  region: "us-east-1"
  upload-dir: "travis-builds"
  file:
    - "target/snapdirector-0.0.1.war"
  access_key_id:
    secure: WGnaBAbjdkEl/NmYLZ9aY294jQwmK4uQIs2MDKFrmbZDTRoKB5cbrjrCKrtH2WyL+1qH8lE+tio+jqjLPUd2tC/ourpsmDypYTZ5ZaeNAqb9Dz5w+eb9eZZXbYs/4MnXVKSvXKx6ua7Hs8Sw4OfKa7VPdT7XQMm6Ibti6znetZ/VECs5fvE8WSbW6qmjpuOYbja+VqLRBpI1Y3Fv5GR4PaGeoowiC+11ZGd53EyUqwvmK10LboWEAmg5Kc8C6qAwY7ELoO59IXV7jgQK0tswISGghYE3gJqupBHfr400G8E9XCUG+WWcUEXzdUiIk3ZU0RVp9fNLst87voy+AUcacbJLbkg5pOpawWgeTmQeOo8r7QvMXoFLC3jj1ra3Fmym7l1Rlv+yXB+/rglxesU0k4QXJHHE9bLuC0t4wYvpCgFuv3cWAZB9JqPCk1WgwiljAUlBY6YC08OsSe+Ne4ezumkKWfjCFkiJ0akLQKG9/ydalBFVDHgw2pkOGU35SIYC67vZoereIyo1LjRPsKPdRCka+wiOyHsxZfOe8ZlQctRmiSN4Huz2Z1TI6uHQTocveQcGNcFJmmwmRHSCVOpjMXCmIU7fI+XfB5bVpL05n3Aq17aC9Oldwikt+Fodb3OlhTe+QfmHIVS03cuWSMcK/TUdTj0mtoeVdyvKdzpuS4I=
  secret_access_key:
    secure: M5Ya6XLZOIIFX47liJkP0mlPR65nWHjE/eaNTlIln989DCzeMRkiK+ZQhY3ha9NXLZflc7HkOMZ7mw/mitdz//upiU7R0fdODlexn8mu0ngTPQhOG73a/+Q2kVTgW1K2JuZ/EWQ3PBaUI/y/ldiU6KqGLsvsCiNl0JYKU/yTCWXkr8vQXwU6zNf9W2IW0PKhdsFwnR+PWk4Cv5seeYnCcahL3GiP8nsXCEc/C1CaVvpsE7QY//UkUCjocyY31+lucNXrc7cTTHEQG0vrGAno99u1pYUTAyYPnGTv1NwXoukBpMguMXpWY22pNaIhVXP2DG0Z5npPerWcYCE62m+APoll6322hEtP1NOs4v6jHKrkriVvjkJmmkNze2Lg8jFZ2+V00Up/iS3otdqCmNujGnoVcswd0dzOWkn/Rstyf/2CBzx0o0aQGz8bwPdC3xcztX7eGUq5hgWeJSapUVKjkaZhqv25YXcssr6bkwHoqcFsv2sb8tcbLM+lZTf8xOchGj+P7Bxr5xh/IUwWFDmm/A/aZOcQjNYKpt0m4hsvdSnYDOWrbqvSeqSBqyKLgQ6AOPzLexecZPNeqXf8wFX1bWW2GuJb2eov9tHjEd1KBCml7KpwPyjvczbkDkMQ2n4JJ7hR60aVUfibObT1A98P3Q8szS1s1vDNoZUrYSa5KfA=
  on:
    branch: java
