---
- name: install OpenJDK 7 JDK
  yum: name="java-1.8.0-openjdk-devel" state=latest

- name: setup JAVA_HOME
  copy: content="export JAVA_HOME=/usr/lib/jvm/java" dest=/etc/profile.d/java_home.sh mode="0755"
